### ISSUE TITLE
Undefined Resource Set - User Details modal

### ISSUE THREAD

**Issue by foster-jason** [UDATech/ChineseTranslation#11]
The following Resource IDs are coming up with ResourceSet= undefined
user_Details
user_Next
user_BackToResults

 It is on a modal that is part of the add user sequence. You can get to this modal by choosing "Add User" after searching for existing COL Users by name or email on the Add User tab of the Contacts page.

<img width="1010" alt="screen shot 2016-12-01 at 1 45 05 pm" src="https://cloud.githubusercontent.com/assets/24235454/20809897/1488c42c-b7cd-11e6-958d-b0fa2f8b970f.png">

**Comment by allenkinzalow** [comment]
The correct resource set for this modal is:

ModalContact

**Comment by foster-jason** [comment]
Thanks Allen, I checked the Resource IDs for the missing translations, they are in place for the all of the untranslated text.

data-resource-id="user_Details" - "User Details" - **TRANSLATED**
data-resource-id="user_Next" - "Next" - **TRANSLATED**
data-resource-id="user_BackToResults" - "Back to Results" - **TRANSLATED**
