### ISSUE TITLE
Gallery - Missing Translation Flags for Empty State

### ISSUE THREAD

**Issue by foster-jason** [UDATech/ChineseTranslation#14]
We are missing translation flags for the following:

![screen-shot-2016-12-06-at-10 10 19-am](https://cloud.githubusercontent.com/assets/24235454/20933013/509c0db6-bb9c-11e6-83a6-13f552cdaa53.png)

<img width="494" alt="screen shot 2016-12-06 at 10 05 51 am" src="https://cloud.githubusercontent.com/assets/24235454/20933035/653ca398-bb9c-11e6-8909-3ce73164dfe3.png">

**Comment by foster-jason** [comment]
Added as item 17 to the "Image Translation Resources" page of "COL Basic - Chinese Translation Status" Google Sheet. We can copy the translations over to localization admin once the ResourceSet and IDs have been fixed.

ZH and ZH H translations are available on the Image Translation Resources Sheet

**Comment by swarduda1** [comment]
Translations added to the "Gallery" resource set and the "New Resources" tab in the "COL Basic" Google Sheet
