### ISSUE TITLE
#modalUpload_DragDrop - Undefined Resource Set

### ISSUE THREAD

**Issue by foster-jason** [UDATech/ChineseTranslation#17]
The Upload modal is missing translations for the Resource IDs listed below:

data-resource-id="upload_To"
data-resource-id="upload_UploadButton"
data-resource-id="upload_Or"
data-resource-id="upload_ClickDrag"
data-resource-id="upload_Close"

They come up as being part of an undefined ResourceSet

<img width="1468" alt="screen shot 2016-12-06 at 1 41 16 pm" src="https://cloud.githubusercontent.com/assets/24235454/20944776/535e4d56-bbca-11e6-874b-4eebdcca7ac0.png">

**Comment by foster-jason** [comment]
Add as item 18 to the Image Translation Resources page of COL Basic - Chinese Translation Status. We can copy the translations over to localization admin once the ResourceSet and IDs have been fixed.

**Comment by allenkinzalow** [comment]
The correct resource set for this modal is:

ModalUploadFile

**Comment by foster-jason** [comment]
ModalUploadFile is completely translated for Chinese Traditional, and Chinese Simplified.

**Comment by swarduda1** [comment]
the resource-ids were created but the static text was not replaced with the appropriate function call, fixed
