### ISSUE TITLE
#modalSettingsTLCLCover - Missing Data Resource IDs

### ISSUE THREAD

**Issue by foster-jason** [UDATech/ChineseTranslation#18]
The strings on the modal have neither Translation flags nor Resource IDs.

<img width="908" alt="screen shot 2016-12-06 at 3 55 01 pm" src="https://cloud.githubusercontent.com/assets/24235454/20945313/5d2ffdfa-bbcc-11e6-9858-1a797803a0c6.png">

**Comment by foster-jason** [comment]
Added as item 16 to the Image Translation Resources page of COL Basic - Chinese Translation Status. We can copy the translations over to localization admin once the ResourceSet and IDs have been fixed.

INVARIANT:
Go Pro and Get More.
Get Connected with your Clients and Subs.

With ClientLink & TeamLink, clients and subs log in and:
View project files & photos
Reply to & send messages
See upcoming milestones
View & approve selections
See change orders
See project budget details
Go Pro Today

**Comment by swarduda1** [comment]
ResourceSet: ModalHelp
Resource IDs already existed and were translated, function calls have been replaced to change the text
