### ISSUE TITLE
Gallery > Album page, id="container_top" - Missing Resource ID for "Sort By:"

### ISSUE THREAD

**Issue by foster-jason** [UDATech/ChineseTranslation#19]
There is a missing resource ID for "Sort By." It does not have a ResourceSet or a Resource ID

<img width="1099" alt="screen shot 2016-12-06 at 4 01 56 pm" src="https://cloud.githubusercontent.com/assets/24235454/20945633/a69644bc-bbcd-11e6-98a1-3312a0c85dd1.png">

**Comment by foster-jason** [comment]
Please let me know when a Resource ID is added so we can get a translation on it ASAP

**Comment by swarduda1** [comment]
Resource Set: Gallery
Resource ID: album_SortBy
Already translated, replaced
