### ISSUE TITLE
Gallery <div id="container_mainContent"> album_SortByFileSize

### ISSUE THREAD

**Issue by foster-jason** [UDATech/ChineseTranslation#21]
There's something going on with the Resource IDs in the option selector with the Resource ID album_SortByFileSize and the Resource ID album_SortByName 

<img width="1150" alt="screen shot 2016-12-07 at 10 54 36 am" src="https://cloud.githubusercontent.com/assets/24235454/20977608/bbbb5668-bc6b-11e6-8a2b-20eb22c23a96.png">

**Comment by foster-jason** [comment]
Please note the duplicate entries Chinese entries:

名稱
名稱File Size

名称 = NAME
文件大小 = FILE SIZE

**Comment by swarduda1** [comment]
Static Text was left over and incorrect id was being used on that line, fixed and closed
