### ISSUE TITLE
class="inline_alert_box  contacts"  -  "Call Log" not translated

### ISSUE THREAD

**Issue by foster-jason** [UDATech/ChineseTranslation#24]
RESOURCE ID: templates_InlineInfoDiv_ProjectMessages

<img width="850" alt="screen shot 2016-12-07 at 11 24 49 am" src="https://cloud.githubusercontent.com/assets/24235454/20978793/d266dea6-bc6f-11e6-8a2f-d9b46a86522b.png">

**Comment by swarduda1** [comment]
that element actually gets replaced with different text (the data-resource-id won't display the correct resource-id), but the translation itself is fixed (id: "documentsDetails_CallLog")
