### ISSUE TITLE
Project Details, project_team section - Contact Type

### ISSUE THREAD

**Issue by foster-jason** [UDATech/ChineseTranslation#25]
when editing a project or template's details, the empty state for contact types contains non-translated elements. It uses one Resource ID and pulls the contact type (I am assuming by JS).

Resource ID: projectDetails_NoUsersSelected
No %type% users have been assigned to this project yet.

![screen_shot_2016-12-07_at_12 14 30_pm](https://cloud.githubusercontent.com/assets/24235454/20982711/4d3522f0-bc7f-11e6-87a0-b0cb7b7ecec3.png)

![screen_shot_2016-12-07_at_12 12 47_pm](https://cloud.githubusercontent.com/assets/24235454/20982726/55ad054c-bc7f-11e6-851b-00c98e69cc0e.png)

![screen_shot_2016-12-07_at_12 14 27_pm_720](https://cloud.githubusercontent.com/assets/24235454/20982766/76c92bac-bc7f-11e6-8842-209be6931663.png)

**Comment by swarduda1** [comment]
Resource Set: Projects
Items added to the New Resources tab in the Google Sheet
