### ISSUE TITLE
Missing Translation - <select class="project_permissions"></select> 

### ISSUE THREAD

**Issue by foster-jason** [UDATech/ChineseTranslation#26]
The Basic User Permissions option selector is missing translations

<img width="1180" alt="screen shot 2016-12-07 at 4 58 03 pm" src="https://cloud.githubusercontent.com/assets/24235454/20990485/a4b74408-bc9e-11e6-899f-e1d157ffd934.png">

![screen shot 2016-12-07 at 4 58 42 pm](https://cloud.githubusercontent.com/assets/24235454/20990476/997bf5de-bc9e-11e6-8a2d-7cbe8c3087b9.png)

**Comment by swarduda1** [comment]
Resource Set: Projects
Tags existed and are translated, replaced
